CREATE TABLE units
(
    id   BIGINT NOT NULL,
    code BIGINT,
    name VARCHAR(255),
    CONSTRAINT pk_units PRIMARY KEY (id)
);

CREATE TABLE products
(
    id           BIGINT NOT NULL,
    audit_id     BIGINT NOT NULL,
    inner_id     UUID,
    name         VARCHAR(255),
    price        DOUBLE PRECISION,
    count        DOUBLE PRECISION,
    frozen_count DOUBLE PRECISION,
    unit_id      BIGINT,
    seller_id    BIGINT,
    catalog_id   BIGINT,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

CREATE TABLE product_catalog
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code VARCHAR(255),
    name VARCHAR(255),
    CONSTRAINT pk_product_catalog PRIMARY KEY (id)
);

ALTER TABLE products
    ADD CONSTRAINT uc_products_audit UNIQUE (audit_id);

ALTER TABLE products
    ADD CONSTRAINT FK_PRODUCTS_ON_AUDIT FOREIGN KEY (audit_id) REFERENCES audits (id);

ALTER TABLE products
    ADD CONSTRAINT FK_PRODUCTS_ON_CATALOG FOREIGN KEY (catalog_id) REFERENCES product_catalog (id);

ALTER TABLE products
    ADD CONSTRAINT FK_PRODUCTS_ON_SELLER FOREIGN KEY (seller_id) REFERENCES organizations (id);

ALTER TABLE products
    ADD CONSTRAINT FK_PRODUCTS_ON_UNIT FOREIGN KEY (unit_id) REFERENCES units (id);
