CREATE TABLE units
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code BIGINT,
    name VARCHAR(255),
    CONSTRAINT pk_units PRIMARY KEY (id)
);

CREATE TABLE product_catalog
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code VARCHAR(255),
    name VARCHAR(255),
    CONSTRAINT pk_product_catalog PRIMARY KEY (id)
);

CREATE TABLE products
(
    id           UUID                        NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    inner_id     UUID                        NOT NULL,
    name         VARCHAR(255)                NOT NULL,
    price        DOUBLE PRECISION            NOT NULL,
    count        INTEGER                     NOT NULL,
    frozen_count INTEGER                     NOT NULL,
    unit_id      BIGINT,
    catalog_id   BIGINT,
    seller_id    UUID                        NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

ALTER TABLE products
    ADD CONSTRAINT FK_PRODUCTS_ON_CATALOG FOREIGN KEY (catalog_id) REFERENCES product_catalog (id);

ALTER TABLE products
    ADD CONSTRAINT FK_PRODUCTS_ON_SELLER FOREIGN KEY (seller_id) REFERENCES organizations (id);

ALTER TABLE products
    ADD CONSTRAINT FK_PRODUCTS_ON_UNIT FOREIGN KEY (unit_id) REFERENCES units (id);

CREATE TABLE contracts
(
    id            UUID                        NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    count         INTEGER                     NOT NULL,
    is_paid       BOOLEAN                     NOT NULL,
    payment_date  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    delivery_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    buyer_id      UUID,
    seller_id     UUID,
    product_id    UUID,
    CONSTRAINT pk_contracts PRIMARY KEY (id)
);

ALTER TABLE contracts
    ADD CONSTRAINT FK_CONTRACTS_ON_BUYER FOREIGN KEY (buyer_id) REFERENCES organizations (id);

ALTER TABLE contracts
    ADD CONSTRAINT FK_CONTRACTS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE contracts
    ADD CONSTRAINT FK_CONTRACTS_ON_SELLER FOREIGN KEY (seller_id) REFERENCES organizations (id);
